### ISSUE TITLE
Adding arbitrary spamass prefs?

### ISSUE THREAD

**Issue by sporkman** [JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL#24]
Hello,

Great plugin, very useful!  One thing I miss from our old squirrelmail sauserprefs plugin is the ability to add arbitrary settings to the user's preferences.  For example, we have an "x-spam-days" value that we store in the userprefs table which our spam-purging script reads to determine how far back to purge the spam folder.

I'm going to probably do a quick local hack to implement this as a clone of the spam score setting since the UI (dropdown select) will be the same, but if I wanted to make it a a bit cleaner and more general, any good starting points to look at?

**Comment by JohnDoh** [comment]
I've just added some new plugin hooks. similar to ones in the core sauserprefs_list and sauserprefs_save should allow you do to what you want

**Comment by sporkman** [comment]
Wow, that looks awesome.  It might be some time before I test it, as I've already made my own hack:

https://gist.github.com/439a97a6c9d09ff32e33.git

It's messy, but easier than I thought, your code is very straightforward and things are named in a very friendly way.
