### ISSUE TITLE
userprefs not working

### ISSUE THREAD

**Issue by schickel007** [JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL#28]
Roundcube Webmail 1.1.2
sauserprefs 1.15-git
SpamAssassin 3.4.1

I've set up everything like described in the HowTo. spamd starts with the required options -x -q (-x -Q). Changing settings in roundcube are stored in MariaDB. But these settings are not used.

I've tested so much and can't get it to work. 

Did you have any other hints for me?

**Comment by JohnDoh** [comment]
The best I can do is direct you to the spamassassin wiki here http://wiki.apache.org/spamassassin/UsingSQL

**Comment by schickel007** [comment]
I've used this how to, but spamassassin is totally ignoring the sql.cf and used default-values.

Nevermind, More than 10 hours of testing and reconfiguring the service and sending testmails is for now enough...

Btw: This documentation is not actual, because MariaDB does not accept "TYPE=MyISAM". It must be "ENGINE = InnoDB"

**Comment by schickel007** [comment]
Ok, after some debugging again I got it now to work....

The sql-query was not correct.
