### ISSUE TITLE
Hiding the setings tab that not needed

### ISSUE THREAD

**Issue by rutkas** [JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL#31]
It would be good to have an option in config to hide that tabs that we do not want to show to the user.
For example I do not want the users to show the first tab I comment the line in sauserprefs.php:
// 'general' => array('id' => 'general', 'section' => $this->gettext('spamgeneralsettings')),
and the tab is dissappearing.. But this tweak will be loosed after update, so the option to list an array of tabs to be hidden would be great.
Actually I want to use only last tab from this plugin, because do not want the users to break main rules, bayes, and other stuff.
thanks

**Comment by JohnDoh** [comment]
This is already possible using the `sauserprefs_dont_override` config option. Details of exactly how to do it are described in comments in the config file.
