### ISSUE TITLE
Unless variables initialization and undefined variables in storage class

### ISSUE THREAD

**Issue by nuxwin** [JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL#39]
Hi,

In the storage class are some unless initialization and also undefined variables:

At line 95, initialization of the `$result variable seem useless as his variable get immediately overridden at line 103. There is similar issues in the class which you could track easily with an IDE such as PhpStorm.

At line 97, 106,t the `$prefs` array is never defined.

Thanks you.

**Comment by JohnDoh** [comment]
I've fixed the variables used in the error log message.

I do not agree about the $result var being useless. the purpose is to set the default/inital value. that way if something unexpected happens it is false. perhaps the code could be written more elegantly but there are other issues around the different types of queries and ensuring that TRUE is returned even when there is nothing do to.

**Comment by nuxwin** [comment]
@JohnDoh 

I totally agreed with you for initialization of variable to TRUE before entering loop but not after. 

In short, I agreed with https://github.com/JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL/blob/master/lib/Roundcube/rcube_sauserprefs_storage_sql.php#L88
I disagreed with:

- https://github.com/JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL/blob/master/lib/Roundcube/rcube_sauserprefs_storage_sql.php#L95
- https://github.com/JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL/blob/master/lib/Roundcube/rcube_sauserprefs_storage_sql.php#L111
- https://github.com/JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL/blob/master/lib/Roundcube/rcube_sauserprefs_storage_sql.php#L129
- https://github.com/JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL/blob/master/lib/Roundcube/rcube_sauserprefs_storage_sql.php#L144
- https://github.com/JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL/blob/master/lib/Roundcube/rcube_sauserprefs_storage_sql.php#L160

Because the value would be immediately overridden by `$result = $this->db->affected_rows()` and here, apart an exception throw and which you should properly catch,  I don't see how the variable could stay set to true when that is not expected.

**Comment by JohnDoh** [comment]
I agree this code could probably be written in a better way however I feel this particlular issue is more a discussion of coding style than a bug.

I'll reopen the ticket as a reminder that the code needs improvement. If you have an idea please feel free to submit a PR.

**Comment by JohnDoh** [comment]
code refactored in 8d9f48a
